config/routes.rb
AppTrunk02a::Application.routes.draw do
  post "infomations/grid"
  resources :infomations
  
  get "report_insure_bills/query"

  get "report_insure_bills/submit"

  get "charts/query"
  
  get "charts/employee"

  get "charts/submit"

  get "report_providents/query"

  get "report_providents/submit"

  get "report_perminum_details/query"

  get "report_perminum_details/submit"

  resources :users
  
  post "sessions/update_password"
  
  get "sessions/unlock"
  
  get "sessions/login"

  get "sessions/logout"

  get "report_emps/query"

  get "report_emps/submit"

  get "cities/cities_tree"
  resources :cities

  post "company_accounts/grid"
  resources :company_accounts

  post "personal_accounts/grid"
  resources :personal_accounts

  post "insure_results_subs/grid"
  resources :insure_results_subs

  get "insure_results/calcs"
  post "insure_results/grid"
  resources :insure_results

  post "employees/grid" , "employees/delete"
  get "employees/insure" , "employees/provident"
  resources :employees

  get "areas/grid"
  resources :areas
  get "cities/grid"
  get "provinces/grid"
  resources :provinces

  resources :tags

  resources :insure_programs

  get "post/grid"

  post "companies/grid" , "companies/delete"
  resources :companies
  

   root :to => 'sessions#login'

   match ':controller(/:action(/:id(.:format)))'
end

app/models/insure_results_sub.rb
class InsureResultsSub < ActiveRecord::Base
  
  scope :with_sum_insure , where(" insure_item > ?" , 1).sum("insure_money")
  
  scope :with_sum_provident , where(" insure_item = ?" , 1).sum("insure_money")
  
  belongs_to :insure_result
  
  
  def sum_insure
     where(" insure_item > ?" , 1).sum("insure_money")
  end
  
  def sum_provident
    where(" insure_item = ?" , 1).sum("insure_money")
  end
  
end

app/controllers/insure_results_subs_controller.rb
class InsureResultsSubsController < ApplicationController
  # GET /insure_results_subs
  # GET /insure_results_subs.json
  def index
    @insure_results_subs = InsureResultsSub.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render :json => @insure_results_subs }
    end
  end
  
  def grid
    @insureResultsSub = InsureResultsSub.where(:main_id => params[:main_id])
    respond_to do |format|
        format.json { render :json => {:success => true , :data => @insureResultsSub , :total => @insureResultsSub.size} }
    end
  end

  # GET /insure_results_subs/1
  # GET /insure_results_subs/1.json
  def show
    @insure_results_sub = InsureResultsSub.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render :json => @insure_results_sub }
    end
  end

  # GET /insure_results_subs/new
  # GET /insure_results_subs/new.json
  def new
    @insure_results_sub = InsureResultsSub.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render :json => @insure_results_sub }
    end
  end

  # GET /insure_results_subs/1/edit
  def edit
    @insure_results_sub = InsureResultsSub.find(params[:id])
  end

  # POST /insure_results_subs
  # POST /insure_results_subs.json
  def create
    @insure_results_sub = InsureResultsSub.new(params[:insure_results_sub])

    respond_to do |format|
      if @insure_results_sub.save
        format.html { redirect_to @insure_results_sub, :notice => 'Insure results sub was successfully created.' }
        format.json { render :json => @insure_results_sub, :status => :created, :location => @insure_results_sub }
      else
        format.html { render :action => "new" }
        format.json { render :json => @insure_results_sub.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /insure_results_subs/1
  # PUT /insure_results_subs/1.json
  def update
    @insure_results_sub = InsureResultsSub.find(params[:id])

    respond_to do |format|
      if @insure_results_sub.update_attributes(params[:insure_results_sub])
        format.html { redirect_to @insure_results_sub, :notice => 'Insure results sub was successfully updated.' }
        format.json { head :ok }
      else
        format.html { render :action => "edit" }
        format.json { render :json => @insure_results_sub.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /insure_results_subs/1
  # DELETE /insure_results_subs/1.json
  def destroy
    @insure_results_sub = InsureResultsSub.find(params[:id])
    @insure_results_sub.destroy

    respond_to do |format|
      format.html { redirect_to insure_results_subs_url }
      format.json { head :ok }
    end
  end
end

app/helpers/insure_results_subs_helper.rb
module InsureResultsSubsHelper
end

app/views/insure_results_subs/_form.html.erb
<%= form_for(@insure_results_sub) do |f| %>
  <% if @insure_results_sub.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@insure_results_sub.errors.count, "error") %> prohibited this insure_results_sub from being saved:</h2>

      <ul>
      <% @insure_results_sub.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :main_id %><br />
    <%= f.number_field :main_id %>
  </div>
  <div class="field">
    <%= f.label :insure_type %><br />
    <%= f.number_field :insure_type %>
  </div>
  <div class="field">
    <%= f.label :insure_base %><br />
    <%= f.text_field :insure_base %>
  </div>
  <div class="field">
    <%= f.label :insure_money %><br />
    <%= f.text_field :insure_money %>
  </div>
  <div class="field">
    <%= f.label :insure_item %><br />
    <%= f.number_field :insure_item %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/insure_results_subs/edit.html.erb
<h1>Editing insure_results_sub</h1>

<%= render 'form' %>

<%= link_to 'Show', @insure_results_sub %> |
<%= link_to 'Back', insure_results_subs_path %>

app/views/insure_results_subs/index.html.erb
<h1>Listing insure_results_subs</h1>

<table>
  <tr>
    <th>Main</th>
    <th>Insure type</th>
    <th>Insure base</th>
    <th>Insure money</th>
    <th>Insure item</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @insure_results_subs.each do |insure_results_sub| %>
  <tr>
    <td><%= insure_results_sub.main_id %></td>
    <td><%= insure_results_sub.insure_type %></td>
    <td><%= insure_results_sub.insure_base %></td>
    <td><%= insure_results_sub.insure_money %></td>
    <td><%= insure_results_sub.insure_item %></td>
    <td><%= link_to 'Show', insure_results_sub %></td>
    <td><%= link_to 'Edit', edit_insure_results_sub_path(insure_results_sub) %></td>
    <td><%= link_to 'Destroy', insure_results_sub, :confirm => 'Are you sure?', :method => :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Insure results sub', new_insure_results_sub_path %>

app/views/insure_results_subs/new.html.erb
<h1>New insure_results_sub</h1>

<%= render 'form' %>

<%= link_to 'Back', insure_results_subs_path %>

app/views/insure_results_subs/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Main:</b>
  <%= @insure_results_sub.main_id %>
</p>

<p>
  <b>Insure type:</b>
  <%= @insure_results_sub.insure_type %>
</p>

<p>
  <b>Insure base:</b>
  <%= @insure_results_sub.insure_base %>
</p>

<p>
  <b>Insure money:</b>
  <%= @insure_results_sub.insure_money %>
</p>

<p>
  <b>Insure item:</b>
  <%= @insure_results_sub.insure_item %>
</p>


<%= link_to 'Edit', edit_insure_results_sub_path(@insure_results_sub) %> |
<%= link_to 'Back', insure_results_subs_path %>